#!/bin/bash
. "$(dirname -- "$0")/_/husky.sh"

branch_name=$(git symbolic-ref --short HEAD)
commit_message=$(<"$1")

if [ "$branch_name" = "hotfix" ]; then
  if [[ "${commit_message}" != *"A corregir por:"* ]]; then
    echo "No existe una persona asignada"
    exit 1
  fi
fi
